# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_donations', '0007_auto_20160719_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=4)),
                ('customSku', models.CharField(max_length=13)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
