# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_donations', '0008_inventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='price',
            field=models.CharField(max_length=7),
        ),
    ]
